name: Secure Build and Release SPK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'OpenList Client SPK release'

permissions:  # 显式声明最小权限
  contents: write  # 仅允许写入仓库内容（发布版本）
  actions: read    # 仅需读取权限（查看工作流状态）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 升级到最新稳定版
        with:
          fetch-depth: 0           # 仅拉取必要提交历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install --user -r ./requirements.txt  # 用户级安装避免全局依赖污染

      - name: Build SPK
        run: |
          mkdir -p package/scripts
          cp -r service package/
          cp -r web package/
          tar -czvf "openlist-client-${{ github.event.inputs.version }}.spk" package/*
          mv *.spk build/          # 统一输出到build目录

      - name: Build artifacts
        run: |
          mkdir -p build
          echo "${{ github.event.inputs.release_notes }}" > build/release.txt
          zip -jr build/release.zip build/*  # 仅打包必要文件

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认token（已自动受限）
        with:
          tag_name: "v${{ github.event.inputs.version }}"  # 动态版本号
          files: |
            build/*.spk
