name: Build SPK Package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y tar gzip jq tree
          pip install pyinstaller
          
      - name: Prepare directory structure
        run: |
          mkdir -p package/{bin,scripts,web}
          [ -d "src/scripts" ] && cp -r src/scripts/* package/scripts/ || touch package/scripts/.keep
          
      - name: Build desktop client
        run: |
          pyinstaller --onefile src/main.py --name openlist-gui
          cp dist/openlist-gui package/bin/
          
      - name: Verify scripts
        run: |
          if [ -z "$(ls -A package/scripts/)" ]; then
            echo "::warning::No scripts found in package/scripts/"
          else
            chmod +x package/scripts/*
          fi
          
      - name: Package SPK
        run: |
          tar -czvf OpenListMount-${{ github.event.inputs.version || '2.1.0' }}.spk \
            -C package \
            --owner=root --group=root \
            INFO bin scripts
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spk-package
          path: OpenListMount-*.spk
