name: Build and Release SPK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'OpenList Client SPK release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: pip install -r ./requirements.txt
        
      - name: Build SPK
        run: |
          mkdir -p package/scripts
          cp -r service package/
          cp -r web package/
          tar -czvf openlist-client-${{ github.event.inputs.version }}.spk package/*

      - name: Build artifacts
        run: |
          mkdir -p build
          echo "Release content" > build/release.txt
          zip -r build/release.zip build/

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE2_TOKEN }}  # 使用自动生成的token
        with:
          tag_name: v1.0.0
          files: |
            build/release.txt
            build/release.zip
