name: Build SPK Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build SPK
        run: |
          mkdir -p package/scripts
          cp -r service package/
          cp -r web package/
          tar -czvf openlist-client.spk package/*
