name: Build SPK Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '2.1.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: sudo apt-get install -y tar gzip
        
      - name: Prepare package
        run: |
          mkdir -p package/{bin,etc,scripts,web}
          cp -r src/* package/
          chmod +x package/scripts/*
          
      - name: Create INFO file
        run: |
          cat > package/INFO <<EOF
          $(cat INFO)
          version="${{ github.event.inputs.version }}"
          EOF
          
      - name: Build SPK
        run: tar -czvf OpenListMount-${{ github.event.inputs.version }}-$(uname -m).spk -C package .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spk-package
          path: OpenListMount-${{ github.event.inputs.version }}-*.spk
