name: Build and Release SPK Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '1.0.0'
      arch:
        description: 'Target architecture'
        required: true
        default: 'x86_64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential tar gzip
        
      - name: Create SPK structure
        run: |
          mkdir -p package/{bin,etc,scripts,web}
          cp -r src/* package/
          chmod +x package/scripts/*
          
      - name: Generate INFO file
        run: |
          cat > package/INFO <<EOF
          package="${{ github.event.inputs.package_name || 'OpenListMount' }}"
          version="${{ inputs.version }}"
          arch="${{ inputs.arch }}"
          maintainer="YourName"
          displayname="OpenList Mount"
          description="Mount OpenList WebDAV"
          install_dep_packages="WebDAVServer:service"
          startable="yes"
          dsmappname="SYNO.SDS.AdminCenter.Application"
          EOF
          
      - name: Create SPK package
        run: |
          tar -czvf ${{ github.event.inputs.package_name || 'OpenListMount' }}-${{ inputs.version }}-${{ inputs.arch }}.spk -C package .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spk-package
          path: ${{ github.event.inputs.package_name || 'OpenListMount' }}-${{ inputs.version }}-${{ inputs.arch }}.spk
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          files: ${{ github.event.inputs.package_name || 'OpenListMount' }}-${{ inputs.version }}-${{ inputs.arch }}.spk
